# Generated by Django 5.2 on 2025-04-16 18:33

import cloudinary.models
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_customuser_avatar"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="last_email_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="last_username_change",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=cloudinary.models.CloudinaryField(
                blank=True,
                max_length=255,
                null=True,
                validators=[
                    users.validators.validate_avatar_file_size,
                    users.validators.validate_avatar_file_extension,
                ],
                verbose_name="avatar",
            ),
        ),
    ]
