# Generated by Django 5.2 on 2025-04-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_customuser_last_email_change_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="Расскажи о себе или напиши что-то крутое 🌟",
                max_length=500,
                verbose_name="Описание профиля",
            ),
        ),
    ]
