# Generated by Django 5.2 on 2025-04-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_season_episode'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
