# Generated by Django 5.2 on 2025-04-05 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0003_anime_poster_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='url_title',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='episode',
            name='url_title',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='season',
            name='url_title',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
