# Generated by Django 5.2 on 2025-04-05 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_anime_url_title_episode_url_title_season_url_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='season',
            name='poster_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
