# Generated by Django 5.2 on 2025-04-05 21:30

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_season_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='poster_url',
        ),
        migrations.RemoveField(
            model_name='season',
            name='poster_url',
        ),
        migrations.AddField(
            model_name='anime',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='season',
            name='poster',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
