# Generated by Django 5.2 on 2025-04-07 16:23

import cloudinary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_remove_anime_poster_url_remove_season_poster_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='url',
        ),
        migrations.AddField(
            model_name='episode',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.CreateModel(
            name='Opening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('url_title', models.SlugField(blank=True, unique=True)),
                ('video', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video')),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='openings', to='anime.anime')),
            ],
        ),
    ]
