# Generated by Django 5.2 on 2025-04-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_remove_episode_url_episode_video_opening'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='video',
            field=models.URLField(blank=True, null=True, verbose_name='Video URL'),
        ),
    ]
