# Generated by Django 5.2 on 2025-04-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_alter_episode_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='url_title',
            field=models.SlugField(blank=True),
        ),
    ]
