# Generated by Django 5.2 on 2025-04-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0009_alter_season_url_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="opening",
            name="external_video_url",
            field=models.URLField(
                blank=True, null=True, verbose_name="Ссылка на внешнее видео"
            ),
        ),
    ]
