# Generated by Django 5.2 on 2025-04-23 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("anime", "0010_opening_external_video_url"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opening",
            name="external_video_url",
        ),
        migrations.AlterField(
            model_name="opening",
            name="video",
            field=models.URLField(blank=True, null=True, verbose_name="Video URL"),
        ),
    ]
