# Generated by Django 5.2 on 2025-04-19 11:20

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='video',
            field=cloudinary.models.CloudinaryField(max_length=255),
        ),
    ]
